skinparam {
  NoteBorderColor #E2011F
  NoteFontColor #616161
  NoteBackgroundColor #FFFFFF
  SequenceBoxFontColor #616161
  SequenceBoxBorderColor #616161
  SequenceBoxBackgroundColor #FFFFFF
  Shadowing false
  Roundcorner 20
}

skinparam sequence {

  ArrowColor #E2011F
  ArrowFontColor #616161
  ArrowThickness 1

  LifeLineBorderColor #E2011F
  LifeLineBackgroundColor #FFFFFF
  LifeLineBorderThickness 1

  ParticipantBorderColor #E2011F
  ParticipantBackgroundColor #FFFFFF
  ParticipantFontColor #616161	

  ActorBackgroundColor #FFFFFF
  ActorBorderColor #E2011F
  ActorFontColor #616161

  GroupBorderColor #E2011F
  GroupFontColor #616161
  GroupHeaderFontColor #616161
  GroupBackgroundColor #E2011F
  GroupBodyBackgroundColor #FFFFFF
  GroupHeaderBackgroundColor #FFFFFF
}

